### ISSUE TITLE
sunssf type errors

### ISSUE THREAD

**Issue by esguti** [TRICERA-energy/sunspec#4]
I am trying to use the example with other model template which has sunssf type. 

To reproduce the error just change the type of the last point in the example file main.go (line 588) from "bitfield32" to "sunssf":
```
            {
                "desc": "Vendor defined events",
                "label": "Vendor Event Bitfield 4",
                "name": "EvtVnd4",
                "size": 2,
                "type": "sunssf"
            }
```

makes the program exits with the following error:

```
$ go run main_server.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x539132]

goroutine 6 [running]:
github.com/TRICERA-energy/sunspec.ceil(0x0, 0x0, 0x0)
	/test/sunspec-go/index.go:30 +0x22
github.com/TRICERA-energy/sunspec.(*ModelDef).Instance.func1(0xc000016eb8, 0x8, 0x0, 0x0, 0x0, 0xc00003ca00, 0x22, 0x2a, 0x0, 0x0, ...)
	/test/sunspec-go/model.go:61 +0x127
github.com/TRICERA-energy/sunspec.(*ModelDef).Instance(0xc0000b26c0, 0xc0000200c8, 0x5b4328, 0x4, 0x3, 0xc000028900, 0x2)
	/test/sunspec-go/model.go:81 +0x122
github.com/TRICERA-energy/sunspec.(*Server).Serve(0xc000028300, 0x5dad40, 0xc00000e0a0, 0x5b4380, 0xc000028280, 0x3, 0x4, 0x0, 0x42d42a)
	/test/sunspec-go/server.go:31 +0x3c0
main.Server()
	/test/sunspec-go/examples/basic/main_server.go:82 +0x9b
main.main.func1(0xc000017460)
	/test/sunspec-go/examples/basic/main_server.go:49 +0x52
created by main.main
	/test/sunspec-go/examples/basic/main_server.go:47 +0x28f
exit status 2
```

Please, could you check why is the program failing?

Thanks!

**Comment by esguti** [comment]
I see the error is just a typo in point.go:65. instead of
` 	case "sunnsf":`
 it should be
`	case "sunssf":`
